<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
 	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 	xmlns:context="http://www.springframework.org/schema/context" 	
 	xmlns:mvc="http://www.springframework.org/schema/mvc" 	
 	xsi:schemaLocation="http://www.springframework.org/schema/beans
		http://www.springframework.org/schema/beans/spring-beans-3.0.xsd
		http://www.springframework.org/schema/context
		http://www.springframework.org/schema/context/spring-context-3.0.xsd
		http://www.springframework.org/schema/mvc
		http://www.springframework.org/schema/mvc/spring-mvc-3.0.xsd">
  
  		
	<import resource="dataSourceContext.xml" />
    <import resource="databaseContext.xml"/>
    
 	<context:annotation-config />
 	
 	<context:component-scan base-package="calculator" />
 	
 	<mvc:annotation-driven /> 
    
	<!-- Default Exception Handler Bean -->
	<bean id="defaultExceptionHandlerTemplate" class="org.springframework.web.servlet.handler.SimpleMappingExceptionResolver" lazy-init="true" abstract="true">
		<property name="defaultErrorView">
			<value>defaultError</value>
		</property>    
	</bean>    
</beans>